# Dataset Preprocessing

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
from google.colab import files
uploaded = files.upload()
dataset = pd.read_csv('Data.csv')

Saving Data.csv to Data.csv


In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #strategy='constant', fill_value=5
X[:, 1:2] = imputer.fit_transform(X[:, 1:2])#second col er missing val change korlam median diye. chaile 1:3 kore 2nd,3rd duto col er miss val e median/mean diye change korte partam
#X = imputer.fit_transform(X) eta eikhetre use korte parbo na karon X er prothom coloumn a non-numeric number ache,tai shuhdhu numeric col gulo sleect kore dite hobe ie khetre
imputer = SimpleImputer(missing_values=np.nan, strategy='median') #strategy='constant', fill_value=5
X[:, 2:3] =imputer.fit_transform(X[:, 2:3]) #third col er missing val chnage korlam constant diye.

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')#(transformers=[('encoder', OneHotEncoder(), [0,2,3])], remainder='passthrough')JODI MULTIPLE Col onehot encoding krote chai...jodi ekta hot encoder, ekta label encoder ekstahe korte chai tahole ak ek tar ek ek naam diye korte hobe jemon ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0]), ('encoder1',LabelEncoder(),[-1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) # y te ektai col tai slicing lagbe na
#X[:,0] = le.fit_transform(X[:,0]) #labelencoding doesn't support more than 1 column
#X[:,3] = le.fit_transform(X[:,3]) if i want to encode multiple column, it have to be used separately each time

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

In [ ]:
print(X_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 30.0 54000.0]]


In [ ]:
print(y_train)

[1 0 0 1 0 1 1 1]


In [ ]:
print(y_test)

[0 0]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) #jehetu 80% training data tai ota diyei fit koriye nilam..pore ei trained datar opor e test data ta k fit koralam **fit_transform er concept theke bujte parbo bhalomoton
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[1.0 0.0 0.0 -0.5978808481167128 -0.4456741293291149]
 [0.0 0.0 1.0 0.05261351463427101 -1.0748611354408064]
 [0.0 0.0 1.0 -0.08131179534387283 -0.13108062627326908]
 [0.0 0.0 1.0 -1.9753983221776195 -1.4943191395152675]
 [1.0 0.0 0.0 0.9518263102018072 1.0224288849314989]
 [1.0 0.0 0.0 1.6405850472322605 1.7564803920618055]
 [0.0 1.0 0.0 0.2630675731713538 -0.13108062627326908]
 [1.0 0.0 0.0 -0.25350147960148617 0.4981063798384225]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 1.984964415747487 2.175938396136267]
 [0.0 1.0 0.0 -1.4588292694047795 -0.8651321334035759]]
