In [ ]:
import numpy as np

Creating array using numpy

In [ ]:
a=np.array([1,2,5,9,4,6,7,3,10,19])
print(a)
print(a.shape)
print(a.size)

[ 1  2  5  9  4  6  7  3 10 19]
(10,)
10


Creating 2D array

In [ ]:
b=np.array([[1,2,3],
            [4,5,14],
            [6,7,8],
            [9,10,11],
            [12,13,15]])
print(b)
print(b.shape)
print(b.size)
print(b[0,2])

[[ 1  2  3]
 [ 4  5 14]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 15]]
(5, 3)
15
3


Creating 3D Array

In [ ]:
c=np.array([[[1,2,3],
             [4,5,6],
            [7,8,9]],
            [[1,2,3],
             [4,5,6],
            [7,8,9]],
            [[1,2,3],
             [4,5,6],
            [7,8,9]]])

print(c)
print(c.shape)
print(c.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)
27


Slicing and Dicing

In [23]:
print(b[2:4, :])
print(b[ : , 1])
print(c[1:3, :,:])

[[ 6  7  8]
 [ 9 10 11]]
[ 2  5  7 10 13]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


Reshaping

In [28]:
print(c.reshape(3,9))
print(c.reshape(c.size))

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
