# Creating Arrays using Numpy :)

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print("mean :", np.mean(arr2d))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
mean : 5.0


In [ ]:
# 3D Array:
data = np.array([
    [
        [6.5, 72],
        [1.0, 80],
        [7.0, 65]
    ],
    [
        [5.5, 78],
        [0.5, 85],
        [6.0, 70]
    ]
])

print("Shape of array:", data.shape)
print("3D Data Array:\n", data)


Shape of array: (2, 3, 2)
3D Data Array:
 [[[ 6.5 72. ]
  [ 1.  80. ]
  [ 7.  65. ]]

 [[ 5.5 78. ]
  [ 0.5 85. ]
  [ 6.  70. ]]]


NumPy-তে slicing (ক্লিকিং) এবং dicing (ডাইসিং) সম্পর্কে ধারণা:
Slicing এবং Dicing হলো অ্যারে থেকে নির্দিষ্ট অংশ বের করার পদ্ধতি। এখানে Slicing দিয়ে আমরা একটি অ্যারে বা মেট্রিক্সের নির্দিষ্ট অংশের sub-array বের করি, আর Dicing মানে হলো একাধিক sub-arrays একসাথে বের করা।

🔹 1. Slicing (ক্লিকিং):
Slicing দ্বারা আমরা একমাত্র একটি অংশ বা সাব-অ্যারে নির্বাচন করি। সাধারণত এটি : এর মাধ্যমে করা হয়, যা নির্দেশ করে যে কতটা অংশ নির্বাচন করা হবে।

Slicing Syntax:
python
Copy
Edit
array[start:stop:step]


start → প্রথম ইনডেক্স (যেখানে থেকে শুরু হবে)

stop → শেষ ইনডেক্স (এটি অন্তর্ভুক্ত হবে না)

step → কতটা করে ধাপে ধাপে এগিয়ে যাবেন




In [ ]:
arr = np.array([10, 20, 30, 40, 50])
slice_arr = arr[1:5]
print("Sliced Array:", slice_arr)

Sliced Array: [20 30 40 50]


🔹 2. Dicing (ডাইসিং):
Dicing হলো slicing এর মতো, কিন্তু এতে একাধিক সাব-অ্যারে তৈরি হয়। সাধারণত 3D অ্যারে বা বড় অ্যারে নিয়ে কাজ করার সময় Dicing বেশি কাজে আসে।

In [ ]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

dice_arr = arr3d[:, 1, :]
print("Diced 3D Array:\n", dice_arr)


Diced 3D Array:
 [[ 4  5  6]
 [10 11 12]]


🎯 উদাহরণ ১: 2D Array Flatten



In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr2d.flatten()
print("Original Array:\n", arr2d)
print("Flattened Array:", flat)

Original Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]


arange(): NumPy এর একটি খুবই শক্তিশালী ফাংশন, যা একটি নির্দিষ্ট পরিসরের মধ্যে সংখ্যার সিকোয়েন্স তৈরি করতে ব্যবহৃত হয়। এটি মূলত range() ফাংশনের মতোই কাজ করে, তবে এতে আরো বেশ কিছু অপশন থাকে, যেমন: step (ধাপ) এবং বিকল্প আউটপুট টাইপ।
📌 Syntax:



numpy.arange([start, ]stop, [step, ], dtype=None)


start: সিকোয়েন্সের প্রথম সংখ্যা (অপশনাল, ডিফল্ট 0)

stop: সিকোয়েন্সের শেষ সংখ্যা (এটি অন্তর্ভুক্ত হয় না)

step: ধাপ (যতটা পরবর্তী মানের মধ্যে বৃদ্ধি হবে) (অপশনাল, ডিফল্ট 1)

dtype: আউটপুট অ্যারের ডেটা টাইপ (অপশনাল)


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
arr = np.arange(0, 5, 0.5)
print(arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
